// Code generated by mockery v2.27.1. DO NOT EDIT.

package intfmocks

import mock "github.com/stretchr/testify/mock"

// JWTStrategy is an autogenerated mock type for the JWTStrategy type
type JWTStrategy struct {
	mock.Mock
}

type mockConstructorTestingTNewJWTStrategy interface {
	mock.TestingT
	Cleanup(func())
}

// NewJWTStrategy creates a new instance of JWTStrategy. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewJWTStrategy(t mockConstructorTestingTNewJWTStrategy) *JWTStrategy {
	mock := &JWTStrategy{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
